server:
  port: 8889

host:
  public: 0.0.0.0
  private: 192.168.153.128
  local: 127.0.0.1

# 数据生成器配置
data:
  # 数据库配置
  database: data_optimize
  # 数据量（默认1000w）
  volume: 15000000
  # 插入数据时的合并数据量（默认2w，较优）
  merge: 40000
  # 插入数据时的最大合并数据量（最大4w）
  max-merge: 40000

# 配置相关数据源 使用 druid 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host.private}:3306/${data.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root




