knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://127.0.0.1:8848/nacos/
    routes:
      - name: 文件服务
        serviceName: file-system
        namespaceId: ca2bf4f6-e411-4b8d-a9ba-2e862a822af3
        location: /v2/api-docs?group=default
        servicePath: /file