host:
  public: 0.0.0.0
  private: 192.168.1.14
  local: 127.0.0.1

# 配置相关数据源 使用HikariCP数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host.private}:3306/file_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root