spring:
  cloud:
    gateway:
      routes:
        - id: file_system
          uri: lb://file-system
          predicates:
            - Path=/file/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1