server:
  port: 8088

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://127.0.0.1:8848/nacos/
    routes:
      - name: 文件服务
        serviceName: file-system
        namespaceId: ceaebcf5-685d-4d5a-93fc-bb67f22e2fb4
        location: /v2/api-docs?group=default
        servicePath: /file